language: rust
rust:
- 1.39.0
- stable
- beta
- nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

env:
  global:
  - TEST_LOG=trace
  - RUST_BACKTRACE=full

before_script:
- rustup component add clippy
- rustup component add rustfmt

script:
- if [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then cargo fmt --all -- --check; fi
- if [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then cargo clippy --all --tests -- -D warnings; fi
- if [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then cargo doc --workspace --no-deps; fi
- cargo test --all
# Feature tests.
- ( cd pubnub-core && cargo test --no-default-features --tests )
- ( cd pubnub-core && cargo test --no-default-features --tests --features mock )
- if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then ( cd pubnub-core && cargo test --no-default-features --tests --features nightly ); fi
- if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then ( cd pubnub-core && cargo test --no-default-features --tests --features mock,nightly ); fi
